### 00 pytorch fundamentals
Links
- https://github.com/mrdbourke/pytorch-deep-learning
- learnpytorch.io


In [ ]:
print("sam is here")

sam is here


In [ ]:
! nvidia-smi

Sun Mar  5 00:34:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    24W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
print(torch.__version__)

1.13.1+cu116


In [ ]:
#intor to tensors - tensors represent multi-dimensional data
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as integer
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([1,3])
vector

tensor([1, 3])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
#matrix
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 3])

In [ ]:
matrix[0]

tensor([1, 2, 3])

In [ ]:
#Tensor - kth dimensional 
TENSOR = torch.tensor([[[2,3,4,4,5,5],[1,2,3,4,6,7]]])
TENSOR.ndim


3

In [ ]:
TENSOR.shape #(1,2,6)

torch.Size([1, 2, 6])

### Random tensors

In [ ]:
#create tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3091, 0.6241, 0.6458, 0.7528],
        [0.7121, 0.8656, 0.4289, 0.7347],
        [0.2793, 0.2879, 0.6219, 0.2156]])

In [ ]:
random_tensor = torch.rand(2,5,4)
random_tensor

tensor([[[0.9015, 0.8569, 0.8180, 0.9208],
         [0.1572, 0.4969, 0.4750, 0.3550],
         [0.5176, 0.8049, 0.9160, 0.3102],
         [0.0511, 0.9787, 0.1772, 0.1290],
         [0.9102, 0.3581, 0.7728, 0.4597]],

        [[0.1824, 0.9592, 0.5438, 0.2788],
         [0.4977, 0.3732, 0.9167, 0.7579],
         [0.3470, 0.5057, 0.8262, 0.2596],
         [0.6984, 0.3865, 0.9395, 0.1329],
         [0.9635, 0.3482, 0.9512, 0.3048]]])

In [ ]:
#random tensor with similar to shape to image
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape,random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
random_img_tensor

tensor([[[0.6256, 0.6188, 0.4660,  ..., 0.5747, 0.5012, 0.5224],
         [0.4838, 0.5375, 0.3013,  ..., 0.0343, 0.8830, 0.4393],
         [0.3928, 0.8145, 0.3373,  ..., 0.0494, 0.8563, 0.0430],
         ...,
         [0.3278, 0.9218, 0.7432,  ..., 0.4039, 0.8437, 0.8721],
         [0.0138, 0.3686, 0.5051,  ..., 0.5688, 0.3571, 0.6260],
         [0.2488, 0.9890, 0.3230,  ..., 0.1954, 0.9320, 0.1939]],

        [[0.1441, 0.4507, 0.0741,  ..., 0.2356, 0.0990, 0.7784],
         [0.5694, 0.9476, 0.7147,  ..., 0.7666, 0.5734, 0.1568],
         [0.5782, 0.7542, 0.2958,  ..., 0.1951, 0.1183, 0.0306],
         ...,
         [0.2086, 0.5711, 0.3096,  ..., 0.6034, 0.0639, 0.6542],
         [0.8028, 0.2201, 0.2564,  ..., 0.9387, 0.1601, 0.7380],
         [0.0275, 0.0409, 0.3866,  ..., 0.9600, 0.3141, 0.1256]],

        [[0.0553, 0.0085, 0.5870,  ..., 0.0874, 0.6243, 0.5885],
         [0.2760, 0.4406, 0.5696,  ..., 0.8869, 0.6854, 0.9178],
         [0.8365, 0.4277, 0.5439,  ..., 0.7507, 0.9499, 0.

In [ ]:
#zeros and ones
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)

In [ ]:
ones.dtype

torch.float32

In [ ]:
#Creating range of tesnsors
torch.arange(start = 0 ,end=1000,step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#Creating tensors like
t = torch.arange(1,11)

In [ ]:
t

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
t_zeros = torch.zeros_like(input=t)
t_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
float_32 = torch.tensor([1,4,5,6,9],dtype=None)
float_32

tensor([1, 4, 5, 6, 9])

In [ ]:
float_32 = torch.tensor([1,4,5,6,9],dtype=torch.float32)
float_32.dtype

torch.float32

In [ ]:
float_32 = torch.tensor([1,4,5,6,9],dtype=torch.float32,device=None,requires_grad=False)
#Requires grad : Means you want to pytorch to keep track of the gradientd during computation
float_32.dtype

torch.float32

In [ ]:
#Change datatype
float_16 = float_32.type(torch.half)
float_16.dtype

torch.float16

In [ ]:
float_16

tensor([1., 4., 5., 6., 9.], dtype=torch.float16)

In [ ]:
float_32

tensor([1., 4., 5., 6., 9.])

In [ ]:
float_16 * float_32

tensor([ 1., 16., 25., 36., 81.])

In [ ]:
#Try some other data types
int_32 = torch.tensor([3,4,5,8,10],dtype=torch.int32)
int_32 * float_16
#still works

tensor([ 3., 16., 25., 48., 90.], dtype=torch.float16)

### Getting information from tensors
- shape
- datatypes
- device

In [ ]:
#create a tensor
tens = torch.rand(3,4)
tens

tensor([[0.5040, 0.4969, 0.3193, 0.1665],
        [0.7143, 0.2688, 0.8117, 0.9485],
        [0.6893, 0.7656, 0.1391, 0.0933]])

In [ ]:
#get data types
print("Data type :",tens.dtype)
print(f'shape of tensor is: {tens.shape}')
print(f"Tensor is on device : {tens.device}")

Data type : torch.float32
shape of tensor is: torch.Size([3, 4])
Tensor is on device : cpu


### Manipulating tensors - Tensor operation
- Addition
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [ ]:
### Manipulating tensors - Tensor operation

tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
#subtract 
tensor - 10


tensor([-9, -8, -7])

In [ ]:
#Try out pytorch inbuilt functions for multiplications
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,3)

tensor([4, 5, 6])

#### Matrix multiplications - element wise and matrix and matrix multiplications(dot product)



In [ ]:
### Matrix multiplications - element wise and matrix and matrix multiplications(dot product)

#elemnt wise operation
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,6,7])
print(tensor1 * tensor2)

tensor([ 4, 12, 21])


In [ ]:
#matrix multiplication
matrix_mult = torch.matmul(tensor1,tensor2)
matrix_mult

tensor(37)

In [ ]:
%%time
value = 0 
for i in range(len(tensor1)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.08 ms, sys: 0 ns, total: 3.08 ms
Wall time: 12.8 ms


In [ ]:
%%time
matrix_mult = torch.matmul(tensor1,tensor2)
matrix_mult


CPU times: user 858 µs, sys: 0 ns, total: 858 µs
Wall time: 580 µs


tensor(37)

In [ ]:
#Conditions for matrix multiplicationd - inner dimension must match - resulting shape is going to be the outter dimension
#tensor3 = torch.matmul(torch.rand(3,2),torch.rand(3,2)) # throws error
tensor3 = torch.matmul(torch.rand(3,2),torch.rand(2,3))
tensor3

tensor([[0.1709, 0.4427, 0.2777],
        [0.1882, 0.4924, 0.3217],
        [0.1604, 0.4189, 0.2714]])

In [ ]:
tensor3 = torch.matmul(torch.rand(3,7),torch.rand(7,4))
tensor3

tensor([[0.8769, 1.3239, 1.2251, 1.1227],
        [1.7993, 2.2664, 1.9693, 1.7321],
        [1.1983, 1.4857, 1.2527, 1.1118]])

In [ ]:
tensor3.shape

torch.Size([3, 4])

In [ ]:
#create some tensor

tensor_a = torch.tensor([[1,2],
                         [4,5],
                         [7,8]]
tensor_b = torch.tensor([[5,6],
                         [8,9],
                         [4,8]])
torch.mm(tensor_a,tensor_b)

RuntimeError: ignored

In [ ]:
#Transposing matrix
transpose_b = tensor_b.T
tensor_b.shape,transpose_b.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_a,transpose_b)

tensor([[ 17,  26,  20],
        [ 50,  77,  56],
        [ 83, 128,  92]])

### Tensor aggregation -min,max,mean,sum e.t.c

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
#Finding mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.dtype

torch.int64

In [ ]:
#finding sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Argmax and argmin

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping ,Stacking, Squeezing and unsqueezing
 - reshape --change shape
 - view - returna view of input tensor but keep the same memor as the original tensor
 -stacking - combining multiple tensors on top of each other
 - Squeezing - removind all "1" dimension
 - unsqueez - add a "1" dimension to target tensor
 - permute - return a view the input with dimensions permuted swapped in a certain way

In [ ]:
#create a tensor
x = torch.arange(1,10)


In [ ]:
x.shape

torch.Size([9])

In [ ]:
#add extra dimesnion
x_reshape1 = x.reshape(1,9)
x_reshape1

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshape2 = x.reshape(3,3)
x_reshape2

tensor([[5, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Chaning view
z = x.view(1,9)
z,z.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#chanages z will change x
z[:,0] = 5
x

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#stacking tensors
x_stack = torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
#squeeze and unsqueeze tensor
x_reshape2.squeeze()

tensor([[5, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x_reshape2.shape

torch.Size([3, 3])

In [ ]:
x_reshape2.squeeze().shape

torch.Size([3, 3])

In [ ]:
tensor = torch.arange(1,10)
print(tensor)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
x = torch.rand(1,9)
x

tensor([[0.0672, 0.3276, 0.3762, 0.7406, 0.2685, 0.8994, 0.1170, 0.7241, 0.9877]])

In [ ]:
x.squeeze()

tensor([0.0672, 0.3276, 0.3762, 0.7406, 0.2685, 0.8994, 0.1170, 0.7241, 0.9877])

In [ ]:
y = torch.rand(1,2,3)
y

tensor([[[0.5849, 0.8860, 0.9697],
         [0.8406, 0.9324, 0.8069]]])

In [ ]:
y_squeeze = y.squeeze()
y_squeeze

tensor([[0.5849, 0.8860, 0.9697],
        [0.8406, 0.9324, 0.8069]])

In [ ]:
#unsqueeze
torch.unsqueeze(y_squeeze,dim=1)

tensor([[[0.5849, 0.8860, 0.9697]],

        [[0.8406, 0.9324, 0.8069]]])

In [ ]:
#permute - rerange the dimnesion of the target
x =  torch.rand(size=(224,224,3))
x

tensor([[[0.7649, 0.7675, 0.6546],
         [0.9649, 0.9695, 0.0501],
         [0.2241, 0.8205, 0.0959],
         ...,
         [0.8060, 0.6619, 0.7183],
         [0.9620, 0.9337, 0.8465],
         [0.5270, 0.3647, 0.8841]],

        [[0.3920, 0.3618, 0.2617],
         [0.4619, 0.9811, 0.6869],
         [0.4618, 0.1918, 0.8475],
         ...,
         [0.6193, 0.7683, 0.5389],
         [0.8871, 0.6961, 0.2661],
         [0.0714, 0.4604, 0.8511]],

        [[0.5247, 0.5412, 0.2583],
         [0.6016, 0.3415, 0.8401],
         [0.5496, 0.5431, 0.1118],
         ...,
         [0.7590, 0.1893, 0.3522],
         [0.0542, 0.9586, 0.3073],
         [0.1384, 0.4460, 0.8856]],

        ...,

        [[0.0615, 0.8530, 0.9860],
         [0.6155, 0.2734, 0.0423],
         [0.8949, 0.3163, 0.0304],
         ...,
         [0.4307, 0.9843, 0.1905],
         [0.4411, 0.7379, 0.4478],
         [0.8217, 0.8240, 0.2133]],

        [[0.0596, 0.9099, 0.1559],
         [0.3153, 0.3547, 0.7004],
         [0.

In [ ]:
x[0,0:2,2:]

tensor([[0.6546],
        [0.0501]])

In [ ]:
#permute original tensor to rearange the axis
x_permute = x.permute(2,0,1)
x_permute

tensor([[[3.7277e-01, 7.9814e-01, 8.3819e-02,  ..., 7.1407e-01,
          9.0169e-02, 9.0310e-01],
         [6.2426e-01, 3.7473e-01, 6.7426e-01,  ..., 6.2493e-01,
          9.3234e-01, 9.7230e-01],
         [9.5071e-01, 2.2795e-03, 1.3401e-01,  ..., 2.6685e-01,
          6.6212e-01, 9.4911e-01],
         ...,
         [5.6038e-01, 6.0959e-01, 5.8277e-01,  ..., 9.7054e-01,
          5.0898e-01, 9.4311e-02],
         [8.9904e-01, 2.7444e-01, 9.2175e-01,  ..., 6.3713e-01,
          9.2641e-01, 6.3934e-01],
         [3.0226e-01, 7.4113e-01, 3.2586e-04,  ..., 1.0809e-01,
          7.9518e-01, 5.9355e-03]],

        [[8.3118e-01, 4.0706e-01, 3.9966e-01,  ..., 8.6724e-01,
          6.0198e-01, 9.7839e-01],
         [8.0784e-01, 7.0321e-01, 7.3587e-01,  ..., 7.2014e-01,
          2.3982e-01, 8.1694e-01],
         [1.1889e-01, 8.5789e-02, 2.5655e-01,  ..., 2.1080e-01,
          4.4837e-01, 3.0829e-01],
         ...,
         [3.3611e-01, 3.8075e-01, 9.8021e-01,  ..., 2.1098e-02,
          3.175

In [ ]:
x

tensor([[[3.7277e-01, 8.3118e-01, 1.2636e-03],
         [7.9814e-01, 4.0706e-01, 8.2612e-01],
         [8.3819e-02, 3.9966e-01, 8.6468e-01],
         ...,
         [7.1407e-01, 8.6724e-01, 1.1887e-01],
         [9.0169e-02, 6.0198e-01, 1.3326e-02],
         [9.0310e-01, 9.7839e-01, 1.0743e-01]],

        [[6.2426e-01, 8.0784e-01, 2.6248e-02],
         [3.7473e-01, 7.0321e-01, 6.3619e-01],
         [6.7426e-01, 7.3587e-01, 3.8031e-01],
         ...,
         [6.2493e-01, 7.2014e-01, 2.0190e-01],
         [9.3234e-01, 2.3982e-01, 7.7514e-01],
         [9.7230e-01, 8.1694e-01, 5.1414e-02]],

        [[9.5071e-01, 1.1889e-01, 6.4203e-01],
         [2.2795e-03, 8.5789e-02, 2.5114e-02],
         [1.3401e-01, 2.5655e-01, 9.4445e-01],
         ...,
         [2.6685e-01, 2.1080e-01, 5.6346e-01],
         [6.6212e-01, 4.4837e-01, 2.1067e-01],
         [9.4911e-01, 3.0829e-01, 9.0290e-01]],

        ...,

        [[5.6038e-01, 3.3611e-01, 6.7099e-01],
         [6.0959e-01, 3.8075e-01, 1.2377e-01]

In [ ]:
## Indexing
tensor = torch.arange(1,10).reshape(1,3,3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
#indexing on tensors
tensor[0][1]

tensor([4, 5, 6])

In [ ]:
tensor[0][2][2]

tensor(9)

In [ ]:
#Get all values of 0 dimension but only the 1 index value of 2nd and 3rd dimension
tensor[:,1,1]


tensor([5])

### Pytorch and numpy

In [ ]:
## Changing numpy array to tenso
import numpy as np

x = np.arange(1,10)
print(x.dtype)
tensor = torch.from_numpy(x)
tensor = tensor.dtype=float32
print(tensor,tensor.dtype)

int64


NameError: ignored

In [ ]:
tensor = torch.ones(7)
numpy = tensor.numpy()
tensor,numpy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [ ]:

t1 = torch.rand(3,3)
t2 = torch.rand(3,3)
t1 , t2

(tensor([[0.2263, 0.7042, 0.6561],
         [0.5587, 0.0999, 0.6377],
         [0.2276, 0.2641, 0.0143]]), tensor([[0.9402, 0.0699, 0.9341],
         [0.8169, 0.7826, 0.3650],
         [0.1280, 0.5860, 0.9944]]))

In [ ]:
print(t1 == t2)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [ ]:
from torch.random import manual_seed
#make random and reproducibles tensor
#set seed
random_seed = 42
torch.manual_seed(random_seed)
tc = torch.rand(3,4)
torch.manual_seed(random_seed)
td = torch.rand(3,4)
print(tc == td)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and pytorch on GPUS for faster computation
- google colab
- Use your own machine
- Use cloud computing -GCP,AWS,AZURE

In [1]:
!nvidia-smi

Fri Mar 10 22:39:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    15W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
#check for gpu access with pytorch 
import torch
torch.cuda.is_available()



True

In [4]:
#set up device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"

In [5]:
device

'cuda'

In [7]:
#count number of devices
torch.cuda.device_count()

1

### Putting tensors in models on a GPU for faster computation

In [10]:
#create a tensor
tensor = torch.tensor([1,2,3])
print(tensor.device)

cpu


In [11]:
#move tensor to GPU if avaialbel
tensor_to_device = tensor.to(device)
tensor_to_device

tensor([1, 2, 3], device='cuda:0')

In [13]:
# Move tensors back to CPU
tensor_to_cpu = tensor_to_device.cpu()
tensor_to_cpu

tensor([1, 2, 3])